name: Deploy to FTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: contains(github.event.head_commit.message, 'deploy')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, intl, pdo, pdo_mysql, xml, curl, json, fileinfo, openssl, tokenizer, bcmath, ctype, dom, gd, iconv, libxml, mysqlnd, simplexml, zip

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Change this to your Node.js version

      - name: Install Node.js dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Remove node_modules
        run: rm -rf node_modules

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-dev

      - name: Generate application key
        run: php artisan key:generate

      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./laravel/

      - name: Clear Laravel cache
        run: php artisan config:cache
